download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cisco-meraki-2.18.1.tar.gz
format_version: 1.0.0
name: meraki
namespace: cisco
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.18.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/cisco/meraki/versions/2.18.1/
