- hosts: MX,MS,MR
  connection: local
  gather_facts: no
  tasks:
    - name: Get ISE Secrets from AWS
      set_fact:
        ise_hostname: "{{ lookup('amazon.aws.aws_secret', 'cpn/ise.ise_hostname', nested=true) }}"
        ise_username: "{{ lookup('amazon.aws.aws_secret', 'cpn/ise.ise_username', nested=true) }}"
        ise_password: "{{ lookup('amazon.aws.aws_secret', 'cpn/ise.ise_password', nested=true) }}"
        radius_secret: "{{ lookup('amazon.aws.aws_secret', 'cpn/ise.radius_secret', nested=true) }}"

    # - debug:
    #     msg: "{{ inventory_hostname }}, Address: {{ ansible_host | default('unknown')}}"
    #   when: primary_ip and primary_ip is ansible.utils.ipv4

    - name: Create Network Device
      when: primary_ip and primary_ip is ansible.utils.ipv4
      cisco.ise.network_device:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify:   false
        ise_debug:    false
        state:        "present"
        name:         "{{ inventory_hostname }}"
        NetworkDeviceIPList:          # list of dicts
          - ipaddress: "{{ primary_ip }}"
            mask: 32
        authenticationSettings:
          networkProtocol: "RADIUS"
          radiusSharedSecret: "{{ radius_secret }}"

