meraki_data:
  networks:
    appliance:
      vpn:
        siteToSiteVpn:
          mode: spoke
          hubs:
            - hubId: N_686235993220611692
              useDefaultRoute: false
            - hubId: N_686235993220682610
              useDefaultRoute: false
    wireless:
      ssids:
        - number: 0
          name: cpn-gov
          enabled: true
          splashPage: Cisco ISE
          # ssidAdminAccessible: false
          authMode: 8021x-radius
          dot11w:
            enabled: false
            required: false
          dot11r:
            enabled: false
            adaptive: false
          encryptionMode: wpa
          wpaEncryptionMode: WPA2 only
          radiusServers:
            - host: 100.100.80.27
              port: 1812
              secret: "{{ radius_secret }}"
              radsecEnabled: false
              openRoamingCertificateId: null
              caCertificate: null
          radiusAccountingEnabled: true
          radiusAccountingServers:
            - host: 100.100.80.27
              port: 1813
              secret: "{{ radius_secret }}"
              radsecEnabled: false
              openRoamingCertificateId: null
              caCertificate: null
          radiusTestingEnabled: false
          radiusServerTimeout: 1
          radiusServerAttemptsLimit: 3
          radiusFallbackEnabled: false
          radiusAccountingInterimInterval: 600
          radiusProxyEnabled: false
          radiusCoaEnabled: true
          radiusCalledStationId: '$NODE_MAC$:$VAP_NAME$'
          radiusAuthenticationNasId: '$NODE_MAC$:$VAP_NUM$'
          radiusAttributeForGroupPolicies: "Airespace-ACL-Name"
          ipAssignmentMode: Bridge mode
          useVlanTagging: true
          defaultVlanId: 10
          radiusOverride: false
          # adminSplashUrl: null
          # splashTimeout: 1440 minutes
          walledGardenEnabled: false
          minBitrate: 11
          bandSelection: Dual band operation
          # perClientBandwidthLimitUp: 0
          # perClientBandwidthLimitDown: 0
          # perSsidBandwidthLimitUp: 0
          # perSsidBandwidthLimitDown: 0
          mandatoryDhcpEnabled: false
          lanIsolationEnabled: false
          visible: true
          availableOnAllAps: true
          availabilityTags: []
          speedBurst:
            enabled: false
    switch:
      accessPolicies:
        - accessPolicyNumber: '1'
          name: 8021X_Multi_Auth_Hybrid
          guestPortBouncing: false
          radiusGroupAttribute: '11'
          radius:
            # criticalAuth:
            #   dataVlanId: 
            #   voiceVlanId: 
            #   suspendPortBounce: false
            # failedAuthVlanId: 
            # reAuthenticationInterval: 
          radiusCoaSupportEnabled: true
          radiusAccountingEnabled: true
          radiusTestingEnabled: false
          radiusServers:
            - host: 100.100.80.27
              port: 1812
              secret: "{{ radius_secret }}"
          radiusAccountingServers:
            - host: 100.100.80.27
              port: 1813
              secret: "{{ radius_secret }}"
          hostMode: Multi-Auth
          accessPolicyType: Hybrid authentication
          # authenticationMethod: my RADIUS server
          increaseAccessSpeed: false
          # guestVlanId: 
          voiceVlanClients: true
          urlRedirectWalledGardenEnabled: false
          dot1x:
            controlDirection: both
    groupPolicies:
      - name: Employee
        scheduling:
          enabled: false
          monday:
            active: true
            from: '00:00'
            to: '24:00'
          tuesday:
            active: true
            from: '00:00'
            to: '24:00'
          wednesday:
            active: true
            from: '00:00'
            to: '24:00'
          thursday:
            active: true
            from: '00:00'
            to: '24:00'
          friday:
            active: true
            from: '00:00'
            to: '24:00'
          saturday:
            active: true
            from: '00:00'
            to: '24:00'
          sunday:
            active: true
            from: '00:00'
            to: '24:00'
        bandwidth:
          settings: network default
          bandwidthLimits:
            limitUp: null
            limitDown: null
        firewallAndTrafficShaping:
          settings: network default
          trafficShapingRules: []
          l3FirewallRules: []
          l7FirewallRules: []
        contentFiltering:
          allowedUrlPatterns:
            settings: network default
            patterns: []
          blockedUrlPatterns:
            settings: network default
            patterns: []
          blockedUrlCategories:
            settings: network default
            categories: []
        splashAuthSettings: network default
        vlanTagging:
          settings: network default
        bonjourForwarding:
          settings: network default
          rules: []
      - name: Contractor
        scheduling:
          enabled: false
          monday:
            active: true
            from: '00:00'
            to: '24:00'
          tuesday:
            active: true
            from: '00:00'
            to: '24:00'
          wednesday:
            active: true
            from: '00:00'
            to: '24:00'
          thursday:
            active: true
            from: '00:00'
            to: '24:00'
          friday:
            active: true
            from: '00:00'
            to: '24:00'
          saturday:
            active: true
            from: '00:00'
            to: '24:00'
          sunday:
            active: true
            from: '00:00'
            to: '24:00'
        bandwidth:
          settings: network default
          bandwidthLimits:
            limitUp: null
            limitDown: null
        firewallAndTrafficShaping:
          settings: network default
          trafficShapingRules: []
          l3FirewallRules: []
          l7FirewallRules: []
        contentFiltering:
          allowedUrlPatterns:
            settings: network default
            patterns: []
          blockedUrlPatterns:
            settings: network default
            patterns: []
          blockedUrlCategories:
            settings: network default
            categories: []
        splashAuthSettings: network default
        vlanTagging:
          settings: network default
        bonjourForwarding:
          settings: network default
          rules: []